syntax = "proto3";

package file;

option go_package = "github.com/UPB-Cientifica-Team07/Repo-STORIO/services/file-service/proto;generated";

service FileService {

  rpc UploadFile(UploadFileRequest) returns (UploadFileResponse);

  rpc GetFile(GetFileRequest) returns (GetFileResponse);

  rpc ListFiles(ListFilesRequest) returns (ListFilesResponse);

  rpc DeleteFile(DeleteFileRequest) returns (DeleteFileResponse);
}

message UploadFileRequest {
  string user_id = 1;
  string file_name = 2;
  string file_type = 3;
  bytes content = 4;
}

message UploadFileResponse {
  bool success = 1;
  string message = 2;
  string file_id = 3;
}

message GetFileRequest {
  string file_id = 1;
}

message GetFileResponse {
  bool success = 1;
  string message = 2;

  FileData file = 3;
}

message ListFilesRequest {
  string user_id = 1;
}

message ListFilesResponse {
  bool success = 1;
  string message = 2;

  repeated FileData files = 3;
}

message DeleteFileRequest {
  string file_id = 1;
}

message DeleteFileResponse {
  bool success = 1;
  string message = 2;
}

message FileData {
  string file_id = 1;
  string user_id = 2;
  string file_name = 3;
  string file_type = 4;
  bytes content = 5;
  int64 size = 6;
  string created_at = 7;
}