// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/analysis.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFileRequest) Reset() {
	*x = AnalyzeFileRequest{}
	mi := &file_proto_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFileRequest) ProtoMessage() {}

func (x *AnalyzeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFileRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyzeFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type AnalyzeFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AnalysisId    string                 `protobuf:"bytes,3,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFileResponse) Reset() {
	*x = AnalyzeFileResponse{}
	mi := &file_proto_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFileResponse) ProtoMessage() {}

func (x *AnalyzeFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFileResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyzeFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnalyzeFileResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *AnalyzeFileResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type GetAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisRequest) Reset() {
	*x = GetAnalysisRequest{}
	mi := &file_proto_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisRequest) ProtoMessage() {}

func (x *GetAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *GetAnalysisRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

type GetAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Analysis      *AnalysisData          `protobuf:"bytes,3,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisResponse) Reset() {
	*x = GetAnalysisResponse{}
	mi := &file_proto_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisResponse) ProtoMessage() {}

func (x *GetAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisResponse.ProtoReflect.Descriptor instead.
func (*GetAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *GetAnalysisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAnalysisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAnalysisResponse) GetAnalysis() *AnalysisData {
	if x != nil {
		return x.Analysis
	}
	return nil
}

type ListAnalysesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalysesRequest) Reset() {
	*x = ListAnalysesRequest{}
	mi := &file_proto_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalysesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysesRequest) ProtoMessage() {}

func (x *ListAnalysesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysesRequest.ProtoReflect.Descriptor instead.
func (*ListAnalysesRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *ListAnalysesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAnalysesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Analyses      []*AnalysisData        `protobuf:"bytes,3,rep,name=analyses,proto3" json:"analyses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalysesResponse) Reset() {
	*x = ListAnalysesResponse{}
	mi := &file_proto_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalysesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysesResponse) ProtoMessage() {}

func (x *ListAnalysesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysesResponse.ProtoReflect.Descriptor instead.
func (*ListAnalysesResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *ListAnalysesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListAnalysesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListAnalysesResponse) GetAnalyses() []*AnalysisData {
	if x != nil {
		return x.Analyses
	}
	return nil
}

type AnalysisData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        string                 `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisData) Reset() {
	*x = AnalysisData{}
	mi := &file_proto_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisData) ProtoMessage() {}

func (x *AnalysisData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisData.ProtoReflect.Descriptor instead.
func (*AnalysisData) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *AnalysisData) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *AnalysisData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalysisData) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *AnalysisData) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalysisData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_analysis_proto protoreflect.FileDescriptor

const file_proto_analysis_proto_rawDesc = "" +
	"\n" +
	"\x14proto/analysis.proto\x12\banalysis\"F\n" +
	"\x12AnalyzeFileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"\x84\x01\n" +
	"\x13AnalyzeFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vanalysis_id\x18\x03 \x01(\tR\n" +
	"analysisId\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\"5\n" +
	"\x12GetAnalysisRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\"}\n" +
	"\x13GetAnalysisResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\banalysis\x18\x03 \x01(\v2\x16.analysis.AnalysisDataR\banalysis\".\n" +
	"\x13ListAnalysesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"~\n" +
	"\x14ListAnalysesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\banalyses\x18\x03 \x03(\v2\x16.analysis.AnalysisDataR\banalyses\"\x9a\x01\n" +
	"\fAnalysisData\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\tR\x06fileId\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2\xf8\x01\n" +
	"\x0fAnalysisService\x12J\n" +
	"\vAnalyzeFile\x12\x1c.analysis.AnalyzeFileRequest\x1a\x1d.analysis.AnalyzeFileResponse\x12J\n" +
	"\vGetAnalysis\x12\x1c.analysis.GetAnalysisRequest\x1a\x1d.analysis.GetAnalysisResponse\x12M\n" +
	"\fListAnalyses\x12\x1d.analysis.ListAnalysesRequest\x1a\x1e.analysis.ListAnalysesResponseBXZVgithub.com/UPB-Cientifica-Team07/Repo-STORIO/services/analysis-service/proto;generatedb\x06proto3"

var (
	file_proto_analysis_proto_rawDescOnce sync.Once
	file_proto_analysis_proto_rawDescData []byte
)

func file_proto_analysis_proto_rawDescGZIP() []byte {
	file_proto_analysis_proto_rawDescOnce.Do(func() {
		file_proto_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)))
	})
	return file_proto_analysis_proto_rawDescData
}

var file_proto_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_analysis_proto_goTypes = []any{
	(*AnalyzeFileRequest)(nil),   // 0: analysis.AnalyzeFileRequest
	(*AnalyzeFileResponse)(nil),  // 1: analysis.AnalyzeFileResponse
	(*GetAnalysisRequest)(nil),   // 2: analysis.GetAnalysisRequest
	(*GetAnalysisResponse)(nil),  // 3: analysis.GetAnalysisResponse
	(*ListAnalysesRequest)(nil),  // 4: analysis.ListAnalysesRequest
	(*ListAnalysesResponse)(nil), // 5: analysis.ListAnalysesResponse
	(*AnalysisData)(nil),         // 6: analysis.AnalysisData
}
var file_proto_analysis_proto_depIdxs = []int32{
	6, // 0: analysis.GetAnalysisResponse.analysis:type_name -> analysis.AnalysisData
	6, // 1: analysis.ListAnalysesResponse.analyses:type_name -> analysis.AnalysisData
	0, // 2: analysis.AnalysisService.AnalyzeFile:input_type -> analysis.AnalyzeFileRequest
	2, // 3: analysis.AnalysisService.GetAnalysis:input_type -> analysis.GetAnalysisRequest
	4, // 4: analysis.AnalysisService.ListAnalyses:input_type -> analysis.ListAnalysesRequest
	1, // 5: analysis.AnalysisService.AnalyzeFile:output_type -> analysis.AnalyzeFileResponse
	3, // 6: analysis.AnalysisService.GetAnalysis:output_type -> analysis.GetAnalysisResponse
	5, // 7: analysis.AnalysisService.ListAnalyses:output_type -> analysis.ListAnalysesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_analysis_proto_init() }
func file_proto_analysis_proto_init() {
	if File_proto_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analysis_proto_goTypes,
		DependencyIndexes: file_proto_analysis_proto_depIdxs,
		MessageInfos:      file_proto_analysis_proto_msgTypes,
	}.Build()
	File_proto_analysis_proto = out.File
	file_proto_analysis_proto_goTypes = nil
	file_proto_analysis_proto_depIdxs = nil
}
